// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-GGcKXUIltQDXU8XItS_ip1j4z1eubk',
    appId: '1:438584112131:web:3d49c71ae104a3c2738a36',
    messagingSenderId: '438584112131',
    projectId: 'shopit-a0992',
    authDomain: 'shopit-a0992.firebaseapp.com',
    storageBucket: 'shopit-a0992.firebasestorage.app',
    measurementId: 'G-BT3WNCCQ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXMA-uPTGj5vhBNyK0-MtGzi7hAQDZOQ',
    appId: '1:438584112131:android:296e9293381e10d5738a36',
    messagingSenderId: '438584112131',
    projectId: 'shopit-a0992',
    storageBucket: 'shopit-a0992.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsAUwWOAGSwScKJDWQ9FbX11eZLYhW-Ck',
    appId: '1:438584112131:ios:b8ea51c49d026c9a738a36',
    messagingSenderId: '438584112131',
    projectId: 'shopit-a0992',
    storageBucket: 'shopit-a0992.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsAUwWOAGSwScKJDWQ9FbX11eZLYhW-Ck',
    appId: '1:438584112131:ios:b8ea51c49d026c9a738a36',
    messagingSenderId: '438584112131',
    projectId: 'shopit-a0992',
    storageBucket: 'shopit-a0992.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx-GGcKXUIltQDXU8XItS_ip1j4z1eubk',
    appId: '1:438584112131:web:18cb4a5cb512d907738a36',
    messagingSenderId: '438584112131',
    projectId: 'shopit-a0992',
    authDomain: 'shopit-a0992.firebaseapp.com',
    storageBucket: 'shopit-a0992.firebasestorage.app',
    measurementId: 'G-BTPQZVZTPY',
  );
}
